[project]
name = "xbot"
version = "0.0.1"
description = "Test xbot"
authors = [{name = "pietrek", email = "pietrek.j@gmail.com"}]
readme = "README.md"
dependencies = [
    "opencv-python",
    "easyocr",
    "mss"
]
requires-python = ">=3.8"
